name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: |
        echo "Server host is set: ${{ secrets.SERVER_HOST != '' }}"
        echo "Username is set: ${{ secrets.SERVER_USERNAME != '' }}"
        echo "SSH key is set: ${{ secrets.SERVER_SSH_KEY != '' }}"

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd warpcast_accounts_shop
          git pull origin main
          docker-compose up --build -d
        debug: true
